### PR TITLE
Implement azure pipeline for CI and user tests

### PR DESCRIPTION
**Pull request by janetxinli**

### CODE REVIEW

**Comment by janetxinli** [comment]
Of course! Would it be helpful to keep the bamfile at all, do you think?

**Comment by lcoombe** [comment]
> Of course! Would it be helpful to keep the bamfile at all, do you think?

I think the BAM file is fine to keep (in case someone has issues with the alignment step) -- it isn't very large, right?

**Comment by janetxinli** [comment]
Nope, only around 370KB. Just pushed those changes!

**Comment by lcoombe** [comment]
Thanks for all this work @janetxinli !

**Comment by janetxinli** [comment]
No problem :)

**Pull request merged**
