### PR TITLE
Update btllib to v1.4.1

### PR DESCRIPTION
**Pull request by lcoombe**

### CODE REVIEW

**Comment by vlad0x00** [comment]
I just noticed that the 1.4.1 release contains the `install` directory, which it shouldn't. I'll fix it and make a quick new 1.4.2 release.

**Comment by lcoombe** [comment]
Ok great sounds good - thanks Vlad!

**Comment by vlad0x00** [comment]
Looks like `install/` isn't included in the release, but was added to this commit. I imagine you installed btllib and just commited `install/` with it. I'll just include a `.gitignore` file in the next btllib release so that when you commit it, `install/` is automatically excluded.

**Comment by lcoombe** [comment]
> Looks like `install/` isn't included in the release, but was added to this commit. I imagine you installed btllib and just committed `install/` with it. I'll just include a `.gitignore` file in the next btllib release so that when you commit it, `install/` is automatically excluded.

Ahh you're totally right - I normally try to remember to `git add` right after I download the new release, but this time I must have done a test compilation and added the files after that. I'll fix that on my end!

**Comment by lcoombe** [comment]
@vlad0x00 - should be fixed now. Would you mind just double checking all looks good now?

**Comment by vlad0x00** [comment]
Looks good to me.

**Pull request merged**
