### PR TITLE
Add sort options

### PR DESCRIPTION
**Pull request by PuneetSS**
- Added sort option parameter to `samtools sort` and `sort`
- Updated README

### CODE REVIEW

**Review by lcoombe — APPROVED** [review]
Great work - thanks Puneet!

**Comment by mmokrejs** [comment]
But this could also be pushed to arcs and probably LINKS source trees as well, right? Why not making the behavior consistent across all your tools?

**Comment by mmokrejs** [comment]
And, more importantly, the SORT_OPTS should not be propagated to both `sort` and `samtools sort` commandlines but only to the former. `samtools sort -S 10G` yields an error. Did you test this, @PuneetSS ?

**Comment by lcoombe** [comment]
Thank you for pointing out that the command options should only be added to `sort`, not `samtools sort` - @PuneetSS will open a fresh PR making that fix. 

I'm not sure that we have a `sort` command (other than `samtools sort`, which as you pointed out shouldn't pass these options) in ARCS or LINKS, but definitely feel free to open a PR in either repo if you had an idea for a different command.

**Pull request merged**
